### ISSUE TITLE
CJS module import is broken on latest

### ISSUE THREAD

**Issue by muratsu** [react-dnd/react-dnd#1468]
**Describe the bug**
Latest CJS packages seem to be broken (9.3.3). Using 9.2.1 works. See codesandbox or the log below:

```
[ error ] ./node_modules/react-dnd-cjs/lib/common/DndContext.js
Module not found: Can't resolve 'dnd-core' in '/mnt/c/dev/foobar/app/node_modules/react-dnd-cjs/lib/common'
{ Error: Cannot find module 'dnd-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
```

**Reproduction**

https://codesandbox.io/embed/wonderful-turing-mqywk

**Comment by martinschayna** [comment]
+1, in my scenario `webpack` build works fine with but `mocha --require @babel/register` (i.e. node environment) gives same faulty result.

Also `/dist/cjs` generated distribution subtree in `react-dnd@9.3.2` seems to be broken, I have tried to hack this in babel configuration via `babel-plugin-module-resolver` just like this but without success:
```
  [
    "babel-plugin-module-resolver",
    {
      alias: {
        "^react-dnd$": "\\0/dist/cjs",
        "^react-dnd-.*$": "\\0/dist/cjs",
        "^dnd-.*$": "\\0/dist/cjs"
      }
    }
  ]
```

Long story short, this rewrite bellow works in `webpack` (with `react-dnd@9.3.2`) and also in `mocha` (with `react-dnd-cjs@9.2.1`) without changes in application source code:
```
  [
    "babel-plugin-module-resolver",
    {
      alias: {
        "^react-dnd$": "\\0-cjs"
      }
    }
  ]
```

**Comment by sarnason** [comment]
Facing this same issue.

**Comment by takotaco** [comment]
I came across this as well

**Comment by sandorfr** [comment]
@martinschayna  did you second snipped worked? I tried a couple things I either get Cannot find dnd-core or 
```
/node_modules/dnd-core/dist/esm/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './interfaces';
```

**Comment by sandorfr** [comment]
Also I noticed that 9.3.3 has not been published for all packages. That seems a bit weird @darthtrevino ?

**Comment by sandorfr** [comment]
I did some more digging around this, 

It appears that .d.ts are not patched, (not sure why at this point as the `scripts/execute_cjs_replacements.js` rules look good to me). 

I believe there's a missing rule in `scripts/execute_cjs_replacements.js` to replace imports in js files as well. So DndContext.js does not try to import from `dnd-core` in `node_modules/react-dnd-cjs/lib/common/DndContext.js:11`.

```javascript
		let jsFromReplaceSpec = {
			files: `${file}/lib/**/*.js`,
			from: esmLibs.map(esmLib => new RegExp(`from '${esmLib}'`, 'g')),
			to: esmLibs.map(esmLib => `from '${esmLib}-cjs'`),
		}
		replace.sync(jsFromReplaceSpec)
```

**Comment by darthtrevino** [comment]
Lame, I'll take a cut at fixing the release process.

**Comment by sandorfr** [comment]
You just committed, some abolute path : https://github.com/react-dnd/react-dnd/search?q=christrevino&unscoped_q=christrevino

```
yarn build
yarn run v1.15.2
$ tsc
error TS6053: File '/Users/christrevino/Workspace/oss/react-dnd/packages/core/react-dnd/src/index.ts' not found.


Found 1 error.

error Command failed with exit code 2.
```

**Comment by sandorfr** [comment]
I cleaned my repo and was able to run the build despite the tsconfig. 

Using yarn link I can have thing working but it seems that the published 9.3.5 packages still don't include the correct files.

**Comment by darthtrevino** [comment]
The CJS builds were always meant to be dynamically generated, so I'm not too worried about absolute paths in them. On `yarn install` they should be regenerated anyway. The only reason they're not in .gitignore was because of an issue with Lerna not being able to detect them if they were.

**Comment by darthtrevino** [comment]
@sandorfr what kinds of errors are you seeing after your build completes?

**Comment by darthtrevino** [comment]
I do see that the typings field is missing in the CJS - I'll do another release for that

**Comment by sandorfr** [comment]
Just the error above https://github.com/react-dnd/react-dnd/issues/1468#issuecomment-518488026, but it was solved by cleaning my repo. I guess the yarn install I did then fixed it.

The only remaining problem is that the 9.3.5 you published does not seem to include the changes when you inspect the tarball you still get the wrong imports. 

If I look at my locally built packages they are fine.

**Comment by darthtrevino** [comment]
I'm removing the absolute URLs from the create_packages script, it should be up in a minute

**Comment by darthtrevino** [comment]
@sandorfr The CJS packages are publishing now at 9.3.6

**Comment by darthtrevino** [comment]
Hmm, I don't think the replacement script is being run when the publish triggers. Digging into that...

**Comment by sandorfr** [comment]
Ok trying it now :)

**Comment by sandorfr** [comment]
it's still the wrong files...
![image](https://user-images.githubusercontent.com/2660262/62514889-ee40ad80-b863-11e9-96c1-38327512200f.png)

**Comment by darthtrevino** [comment]
Lerna must be setting up yarn links or something - give me a minute

**Comment by darthtrevino** [comment]
Thanks for your patience, I apologize for cutting a bunch of patches in a row. Those probably should have been prereleases.

**Comment by sandorfr** [comment]
> Thanks for your patience, I apologize for cutting a bunch of patches in a row. Those probably should have been prereleases.

Thanks for the reactivity :) I know how painful this kind of issue are. So I can relate :)

**Comment by sandorfr** [comment]
the correct version will be 3.5.8?

**Comment by darthtrevino** [comment]
9.3.9 hopefully - 9.3.8 doesn't have lib/ directories. Something was jacked up with how the prepublishOnly script was executing.

**Comment by darthtrevino** [comment]
9.3.9 looks good on my end

**Comment by martinschayna** [comment]
> @martinschayna did you second snipped worked? I tried a couple things I either get Cannot find dnd-core or

@sandorfr yes, it works with given older versions of `react-dnd@9.3.2` and `react-dnd-cjs@9.2.1` installed. I haven't tried it yet with newer versions, but I'm looking forward to remove my ugly hack from babel config :slightly_smiling_face:

**Comment by sandorfr** [comment]
> 9.3.9 looks good on my end

It does look good 💃. I will defintely know once the CI completes :)

**Comment by darthtrevino** [comment]
I'm out until the 20th - feel free to reopen this if the problem persists. Thanks!

**Comment by fabien-h** [comment]
Can you publish on npm ? The lastest available is 9.3.4 as of today https://www.npmjs.com/package/react-dnd

**Comment by sandorfr** [comment]
> Can you publish on npm ? The lastest available is 9.3.4 as of today https://www.npmjs.com/package/react-dnd

the fix in question only applies / affects cjs releases:  https://www.npmjs.com/package/react-dnd-cjs
