### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by ND56** [react-dnd/react-dnd#3626]
## The Issue

- Tests fail when executed due to unexpected react-dnd syntax:
- ![image](https://github.com/react-dnd/react-dnd/assets/32069832/e0d61cc9-4bd8-43b9-a077-ab9363f0baa0)

## Relevant Package Versions / Background

- App bootstrapped with "create react app"
- "react": "18.2.0"
- "react-dnd": "^16.0.1",
- "react-dnd-html5-backend": "^16.0.1",

## This Issue Was Previously Reported

- Looks like this issue was previously reported and was ostensibly resolved: https://github.com/react-dnd/react-dnd/issues/1458
- The guidance there was to use jest's `moduleNameMapper` to resolve the issue
- However, based on the comment thread in that issue, it looks like that was allegedly no longer necessary?
- Either way, trying it now did not resolve my issue:
- <img width="471" alt="image" src="https://github.com/react-dnd/react-dnd/assets/32069832/99e840c5-f97c-4f56-a875-1f1d881e5759">
- ![image](https://github.com/react-dnd/react-dnd/assets/32069832/1fbad878-d9e6-4f00-a603-f88024e2f5ea)

## Question

Any other advice on how we can resolve this?

Thanks!

**Comment by ND56** [comment]
I can resolve the error by adding this jest override, but I'm just wondering if there's any other recommended approach:

```json
  "jest": {
    "transformIgnorePatterns": [
      "/node_modules/react-dnd/dist/index/"
    ]
  }
```

**Comment by abglassford** [comment]
> I can resolve the error by adding this jest override, but I'm just wondering if there's any other recommended approach:
> 
> ```json
>   "jest": {
>     "transformIgnorePatterns": [
>       "/node_modules/react-dnd/dist/index/"
>     ]
>   }
> ```

I have the same issue as OP. Tried what he mentioned above with `transformIgnorePatterns` with no success.

**Comment by kaqiinono** [comment]
how can i fix it when use react-dnd in the package @dp/components which cause problems below 
![image](https://github.com/user-attachments/assets/964c3a1e-13ce-4e28-9f6a-f08a11daf55f)
transformIgnorePatterns and transform config cannot solve the problem at all

**Comment by mrrobrob** [comment]
this started occurring for me when i upgraded from typescript 5.5.4 to 5.6.x. Rolling back to typescript 5.5.4 stops this issue occurring for me.

**Comment by zuhlke-rex** [comment]
> when I set it like this:
> 
> ```
> module.exports = {
>   ...a bunch of stuff,
>   transformIgnorePatterns: [
>     'node_modules/(?!@<some package here>|react-dnd|core-dnd|@react-dnd|dnd-core|react-dnd-html5-backend)',
>   ],
> }
> ```
> 
> It did!


I faced the same issue and got over it with the jest config above. Jest runs but faced another issue running my test:
Partial snippets:
```
  it("render as expected", () => {
    const { container } = customRender(
      <DndProvider backend={HTML5Backend}>
        <Component {...baseProps} />
      </DndProvider>,
    );
    expect(container).toMatchSnapshot();
  });
```
And got an exception below:

```
      detail: TypeError: (0 , fast_deep_equal_1.default) is not a function
          at ./node_modules/react-dnd/dist/hooks/useCollector.js:16:19
```

The error comes from a dependency `react-dnd` uses which is not a function. 🤔 Does anyone have any clues?
